logging:
  level:
    org:
      springframework:
        orm:
          jpa: INFO
          jpa.JpaTransactionManager: DEBUG
        transaction: INFO
        transaction.interceptor: TRACE

spring:
  config:
    activate:
      on-profile: ci,test
  application:
    name: shareit
  #  datasource:
  #    driver-class-name: org.postgresql.Driver
  #    password: 12345
  #    url: jdbc:postgresql://localhost:5432/shareit
  #    username: dbuser
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:shareit
    username: test
    password: test
  jpa:
    show-sql: true
    properties:
      hibernate.jdbc.time_zone: UTC
    hibernate:
      ddl-auto: none
    generate-ddl: false
  main:
    banner-mode: 'OFF'
  sql:
    init:
      mode: always
